fixtures:
  forge_modules:
    apt:
      repo: "puppetlabs/apt"
      ref: "2.0.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "1.0.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.18.0"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
      ref: "1.0.0"
  symlinks:
    blackfire: "#{source_dir}"
