sudo: false
language: ruby
bundler_args: "--no-deployment"

before_script:
- puppet --version

script:
- bundle exec rake validate
- bundle exec rake lint
- bundle exec rake spec

matrix:
  fast_finish: true
  include:
  - rvm: 2.5
    env: PUPPET_VERSION="~> 5" DEPLOY="yes"
  - rvm: 2.4
    env: PUPPET_VERSION="~> 5.4"
  - rvm: 2.3.1
    env: PUPPET_VERSION="~> 4.6"
  - rvm: 2.2.5
    env: PUPPET_VERSION="~> 4.3"
  - rvm: 2.1.10
    env: PUPPET_VERSION="~> 4.2"

before_deploy:
- bundle exec puppet module build

deploy:
  provider: releases
  api-key:
      secure: MGxLG561b5JH6nEi2Pbd1BfD/rGH9vzCAs6bW/LZg68z9y7+i4l66otBz9I9WZWGY/smXKWoO8L/VTLS6yvv2zgSIbJkop1h5/1+CDQRywZhaxAiJFMmONp/rTSSmL+vsBDftbqvtTsQBVb0ewhCAf5LKC8XXQKldvhjz813Pt2O+TRp7MF6loGaDMbSMeKiSgrprcUc/6YAohP3bso7Q9OAxpKQGINg1kuZxqVGUYyOlFzxp4IFiEOo+kHZuqq9aliQbn6qcPYxVFiXk1h6NX/Ibgydj/MuXTZa3Y2t6wHllVOY1scB3KCZGYEEWT+hlojA/RdU0SEUxtxnitozkcO7S19mYnvyvHByjJ9ZTNCXtt+ELsh7upCCrLRl2CB++p6HyCk2crAkiGEPIgRSU9Wy67IS+YsdMVJk6+Uy7JS1tJraAJdgKnAlwte1aQNvbLphANrqm3+gcZxulvIxDUGRQISiofL+kzXL+G3bYkDMQu62vj2IzAZKqdVXZ/QRTMrIwrNYEH6FBOIlTT1THj3+mz6kz7RVwj298mVEyqWODycJc+u/ZvnArC7aoCnmlop/tFaUJTDESDAiVPF3c8b4wAx16lariwK52+r6RPyNjmEDFKjJfwbOIPll0tOYvjWOwZIozO/OoeWGbeug2NWdGGJ9JAjEV3n7m00izq8=
  file: "$(ls $TRAVIS_BUILD_DIR/pkg/s12v-blackfire-*.tar.gz | head -n 1)"
  skip_cleanup: true
  on:
    repo: s12v/puppet-blackfire
    tags: true
    all_branches: true
    condition: $DEPLOY = yes
